### PR TITLE
Google analytics

### PR DESCRIPTION
**Pull request by nparsons08**
GA, OG, Pinterest & Twitter support.

### CODE REVIEW

**Comment by tschellenbach** [comment]
Does this work for url based tracking? Try the google analytics extension https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en

**Comment by tschellenbach** [comment]
https://i.imgur.com/P7cixcR.png maybe better to use a screenshot of the app?

**Comment by nparsons08** [comment]
@tschellenbach https://cl.ly/2A1434153a3f

**Comment by nparsons08** [comment]
@tschellenbach Updated OG images to https://i.imgur.com/ALFAcHQ.png.

**Pull request merged**
